runtime:
  cache_dir: ./.cache/antora

site:
  title: Modern Application Development Roadshow - Dev Track
  start_page: mad-dev-guides-m6::1-introduction.adoc

content:
  sources:
    - url: .
      branches: main
      start_path: documentation

asciidoc:
  attributes:
    experimental: true
    page-pagination: true
    openshift-password: openshift
  extensions:
    - ./lib/remote-include-processor.js
    - ./lib/tab-block.js

antora:
  extensions:
    - require: '@sntke/antora-mermaid-extension'
      mermaid_library_url: https://cdn.jsdelivr.net/npm/mermaid/dist/mermaid.min.js
      script_stem: header-scripts


ui:
  bundle:
    url: https://github.com/danieloh30/course-ui/raw/main/ui-bundle-fix-rexp.zip
    snapshot: true
  supplemental_files: ./supplemental-ui

output:
  dir: ./gh-pages
